### ISSUE TITLE
add test suite

### ISSUE THREAD

**Issue by ofbeaton** [ofbeaton/db-ping#6]
There is some difficulty because the actual db servers must be stubbed, but as issue #5 shows there is value in having some basic output tests. Let's keep it high level so we don't have to redo the tests all the time as we add engines.

**Comment by shadiakiki1986** [comment]
I already added a test for the case of "no server"

**Comment by ofbeaton** [comment]
added in PR#8

**Comment by ofbeaton** [comment]
Thank you very much!
